@startuml
[*] --> Empty
Empty --> Active : Start task
Failing --> Active : Start task
OutdatedRunning --> OutdatedStopped : Stop task
OutdatedStopped --> Active : Start task
Active --> Active: No action

Empty: env1:v2:No tasks
Failing: env1:v2:Stopped
OutdatedRunning: env1:v1:Running
OutdatedStopped: env1:v1:Stopped
Active: env1:v2:Running
note  "Environment: env1; TaskDefinitionArn: v2" as N1
@enduml